name: 'Semantic Pull Request'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5.3.0
        with:
          wip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SHEPHERD_TOKEN }}
